import type { BrowserState } from "@/types";

export const DATA_BROWSER_STATE: BrowserState = {
  today: [
    {
      key: "1",
      img: "chrome.png",
      name: "Google Chrome",
      session: "192,345",
      bounceRate: "7.5%",
      cte: "19025",
      goalRate: "92%",
    },
    {
      key: "2",
      img: "firefox.png",
      name: "Mozilla Firefox",
      session: "122,345",
      bounceRate: "4.5%",
      cte: "13025",
      goalRate: "90%",
    },
    {
      key: "3",
      img: "microsoft-edge.png",
      name: "Microsoft Edge",
      session: "132,345",
      bounceRate: "4.5%",
      cte: "12025",
      goalRate: "90%",
    },
    {
      key: "4",
      img: "opera.png",
      name: "Opera Browser",
      session: "92,345",
      bounceRate: "2.5%",
      cte: "12025",
      goalRate: "89%",
    },
    {
      key: "5",
      img: "safari.png",
      name: "Apple Safari",
      session: "72,345",
      bounceRate: "1.5%",
      cte: "12025",
      goalRate: "79%",
    },
  ],
  week: [
    {
      key: "1",
      img: "safari.png",
      name: "Apple Safari",
      session: "392,345",
      bounceRate: "9.5%",
      cte: "16025",
      goalRate: "94%",
    },
    {
      key: "2",
      img: "chrome.png",
      name: "Google Chrome",
      session: "212,345",
      bounceRate: "7.5%",
      cte: "13025",
      goalRate: "91%",
    },
    {
      key: "3",
      img: "microsoft-edge.png",
      name: "Microsoft Edge",
      session: "133,345",
      bounceRate: "6.5%",
      cte: "22025",
      goalRate: "90%",
    },
    {
      key: "4",
      img: "opera.png",
      name: "Opera Browser",
      session: "112,345",
      bounceRate: "5.5%",
      cte: "12425",
      goalRate: "88%",
    },
    {
      key: "5",
      img: "firefox.png",
      name: "Mozilla Firefox",
      session: "111,345",
      bounceRate: "2.5%",
      cte: "12125",
      goalRate: "82%",
    },
  ],
  month: [
    {
      key: "1",
      img: "microsoft-edge.png",
      name: "Microsoft Edge",
      session: "333,345",
      bounceRate: "9.5%",
      cte: "13925",
      goalRate: "96%",
    },
    {
      key: "2",
      img: "firefox.png",
      name: "Mozilla Firefox",
      session: "242,345",
      bounceRate: "8.5%",
      cte: "13025",
      goalRate: "91%",
    },
    {
      key: "3",
      img: "chrome.png",
      name: "Google Chrome",
      session: "145,345",
      bounceRate: "3.5%",
      cte: "14025",
      goalRate: "89%",
    },
    {
      key: "4",
      img: "safari.png",
      name: "Apple Safari",
      session: "177,345",
      bounceRate: "4.5%",
      cte: "16025",
      goalRate: "87%",
    },
    {
      key: "5",

      img: "opera.png",
      name: "Opera Browser",
      session: "92,345",
      bounceRate: "1.5%",
      cte: "11025",
      goalRate: "76%",
    },
  ],
};
