export const DATA_MESSAGE_TAB = [
  {
    key: 1,
    name: "notify",
    badgeProps: { type: "warning" },
    list: [
      {
        id: 1,
        icon: "mage:message-dots",
        title: "You have received 5 new messages",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        date: "2023-06-01",
      },
      {
        id: 2,
        icon: "mage:message-dots",
        title: "Admin 1.0.0 release is in the works",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        date: "2023-06-16",
      },
      {
        id: 3,
        icon: "mage:message-dots",
        title: "Admin 0.9.0 release is in the works",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        date: "2023-06-07",
      },
    ],
  },
  {
    key: 2,
    name: "information",
    badgeProps: { type: "success" },
    list: [
      {
        id: 1,
        title: "Project News",
        icon: "proicons:info",
        description: "Admin wrote some casually on the workbench page just now, so I can read it!",
        date: "2021-11-07 22:45:32",
      },
      {
        id: 2,
        title: "Project News 1",
        icon: "proicons:info",
        description: "Admin is busy writing project documentation for soybean-admin!",

        date: "2021-11-03 20:33:31",
      },
      {
        id: 3,
        title: "Project News 2",
        icon: "proicons:info",
        description: "Admin is getting ready for the release of soybean-admin 1.0!",
        date: "2021-10-31 22:43:12",
      },
      {
        id: 4,
        title: "Project News 3",
        icon: "proicons:info",
        description: "Admin submitted a bug to soybean-admin, the multi-tab bar will not be adaptive.",
        date: "2021-10-27 10:24:54",
      },
      {
        id: 5,
        title: "Project News 4",
        icon: "proicons:info",
        description: "Admin created the open source project soybean-admin on May 28, 2021!",
        date: "2021-05-28 22:22:22",
      },
    ],
  },
  {
    key: 3,
    name: "to do",
    badgeProps: { type: "info" },
    list: [
      {
        id: 1,
        icon: "ri:calendar-todo-line",
        title: "Cache Theme Configuration",
        description: "The task is being planned",
        date: "2022-06-17",
        tagTitle: "Not started",
        tagProps: { type: "default" },
      },
      {
        id: 2,
        icon: "ri:calendar-todo-line",
        title: "Add lock screen component, global Iframe component",
        description: "The task is being planned",
        date: "2022-06-17",
        tagTitle: "Not started",
        tagProps: { type: "default" },
      },
      {
        id: 3,
        icon: "ri:calendar-todo-line",
        title: "Example page perfect",
        description: "The task is being planned",
        date: "2022-06-17",
        tagTitle: "Not started",
        tagProps: { type: "default" },
      },
      {
        id: 4,
        icon: "ri:calendar-todo-line",
        title: "Form, Table Example",
        description: "The task is being planned",
        date: "2022-06-17",
        tagTitle: "Not started",
        tagProps: { type: "default" },
      },
      {
        id: 5,
        icon: "ri:calendar-todo-line",
        title: "Performance optimization (optimize recursive function)",
        description: "The task is being planned",
        date: "2022-06-17",
        tagTitle: "Not started",
        tagProps: { type: "default" },
      },
      {
        id: 6,
        icon: "ri:calendar-todo-line",
        title: "Lite version (new branch thin)",
        description: "The task is being planned",
        date: "2022-06-17",
        tagTitle: "Not started",
        tagProps: { type: "default" },
      },
    ],
  },
];
