import type { EventData } from "@/interfaces/IEvents";
export const DATA_EVENTS: EventData = {
  today: [
    {
      id: 1,
      type: "primary",
      title: "Planning for new dashboard wireframe and prototype design",
      date: "19",
      month: "March",
      time: "08:30 AM",
    },
    {
      id: 2,
      type: "secondary",
      title: "International Web Conference 2021",
      date: "19",
      month: "March",
      time: "09:30 AM",
    },
    {
      id: 3,
      type: "info",
      title: "Dribble Designer Meetup",
      date: "19",
      month: "March",
      time: "10:30 AM",
    },
    {
      id: 4,
      type: "warning",
      title: "Dribble Designer Meetup",
      date: "19",
      month: "March",
      time: "11:30 AM",
    },
  ],
  week: [
    {
      id: 1,
      type: "primary",
      title: "Planning for new dashboard wireframe and prototype design",
      date: "12",
      month: "September",
      time: "08:30 AM",
    },
    {
      id: 2,
      type: "info",
      title: "International Web Conference 2021",
      date: "16",
      month: "September",
      time: "09:30 AM",
    },
    {
      id: 3,
      type: "secondary",
      title: "Dribble Designer Meetup",
      date: "15",
      month: "September",
      time: "10:30 AM",
    },
    {
      id: 4,
      type: "warning",
      title: "Dribble Designer Meetup",
      date: "13",
      month: "September",
      time: "11:30 AM",
    },
  ],
  month: [
    {
      id: 1,
      type: "primary",
      title: "Planning for new dashboard wireframe and prototype design",
      date: "24",
      month: "April",
      time: "08:30 AM",
    },
    {
      id: 2,
      type: "secondary",
      title: "International Web Conference 2021",
      date: "24",
      month: "April",
      time: "09:30 AM",
    },
    {
      id: 3,
      type: "info",
      title: "Dribble Designer Meetup",
      date: "24",
      month: "April",
      time: "10:30 AM",
    },
    {
      id: 4,
      type: "warning",
      title: "Dribble Designer Meetup",
      date: "28",
      month: "April",
      time: "11:30 AM",
    },
  ],
};
